#!/usr/bin/env bash
# territory-guard.sh — PreToolUse[Edit|Write|NotebookEdit] hook (generated by scaffold-generate).
# Mechanically enforces the orchestrator-territory rule for IMPLEMENTER sessions only.
# The canonical human-readable statement of this list is the "must NOT touch" list in
# apps/api/CLAUDE.md — this script is its enforcement, not a second source; scaffold-generate
# derives the concrete paths below from the same manifest values.
# No team-registry entry for this session => solo/bootstrap/generation session => no-op.
# Exit 2 blocks the tool call; the stderr message reaches the agent.

set -euo pipefail
command -v jq >/dev/null 2>&1 || exit 0

payload=$(cat)
sid=$(printf '%s' "$payload" | jq -r '.session_id // empty')
reg="$HOME/.claude/team-registry/${sid}.json"
[ -n "$sid" ] && [ -f "$reg" ] || exit 0
role=$(jq -r '.role // empty' "$reg" 2>/dev/null || true)
[ "$role" = "implementer" ] || exit 0

fp=$(printf '%s' "$payload" | jq -r '.tool_input.file_path // .tool_input.notebook_path // empty')
[ -n "$fp" ] || exit 0
rel="${fp#"${CLAUDE_PROJECT_DIR:-$PWD}"/}"

# Orchestrator territory — filled from manifest values at generation.
TERRITORY=(
  "IMPLEMENTATION_PLAN.md"
  "ARCHITECTURE.md"
  "CLAUDE.md"
  "apps/api/CLAUDE.md"
  "apps/api/LESSONS.md"
  "apps/web/CLAUDE.md"
  "apps/web/LESSONS.md"
  "docs/briefs/"
  "docs/runbooks/"
  "docs/audits/"
  "docs/orchestrator-briefing.md"
  "docs/tdd-brief-template.md"
)
# NOTE: scope to the orchestrator's specific docs/ subpaths (matching the canonical
# "must NOT touch" list in apps/api/CLAUDE.md) — NOT a blanket "docs/", which wrongly
# blocked docs/sessions/ (implementer's /session-end) + docs/team-handoffs/ (lead's /team-end).

for t in "${TERRITORY[@]}"; do
  case "$rel" in
    "$t" | "$t"*)
      echo "BLOCKED (territory-guard): '$rel' is orchestrator territory — implementers flag it at Step 9 and the orchestrator writes it hot (canonical list: the 'must NOT touch' list in apps/api/CLAUDE.md)." >&2
      exit 2 ;;
  esac
done

exit 0
