const RAW_ALLOWED_RATERS = [
  "michael.habermas@challenger.gauntletai.com",
  "ruijing.wang@challenger.gauntletai.com",
  "adam.foosaner@challenger.gauntletai.com",
  "adam.mork@challenger.gauntletai.com",
  "alexander.chan@challenger.gauntletai.com",
  "andrew.truong@challenger.gauntletai.com",
  "austin.wade@challenger.gauntletai.com",
  "brent.gibson@challenger.gauntletai.com",
  "bryann.alarcon@challenger.gauntletai.com",
  "cameron.candelori@challenger.gauntletai.com",
  "carter.tune@challenger.gauntletai.com",
  "christopher.king@challenger.gauntletai.com",
  "cody.clayton@challenger.gauntletai.com",
  "cory.vandenberg@challenger.gauntletai.com",
  "david.taylor@challenger.gauntletai.com",
  "dean.iwuchukwu@challenger.gauntletai.com",
  "dhairya.surana@gfachallenger.gauntletai.com",
  "erick.andrade@challenger.gauntletai.com",
  "grace.huang@challenger.gauntletai.com",
  "gustavo.cruz@gfachallenger.gauntletai.com",
  "harry.fezeu@challenger.gauntletai.com",
  "heila.shahidi@challenger.gauntletai.com",
  "hirom.alarcon@challenger.gauntletai.com",
  "ian.kinskey@challenger.gauntletai.com",
  "jake.kinchen@challenger.gauntletai.com",
  "james.hamil@challenger.gauntletai.com",
  "jason.dijols@challenger.gauntletai.com",
  "jay.godfrey@challenger.gauntletai.com",
  "jay.wolberg@challenger.gauntletai.com",
  "jesse.walberg@challenger.gauntletai.com",
  "jimmy.muller@challenger.gauntletai.com",
  "johnny.chung@challenger.gauntletai.com",
  "jordan.ballard@gfachallenger.gauntletai.com",
  "julian.stancioff@gfachallenger.gauntletai.com",
  "keith.mazanec@challenger.gauntletai.com",
  "kevin.ferretti@challenger.gauntletai.com",
  "lianjin.huang@challenger.gauntletai.com",
  "matthew.daw@challenger.gauntletai.com",
  "matthew.johnson@challenger.gauntletai.com",
  "melissa.hargis@challenger.gauntletai.com",
  "michael.moran@challenger.gauntletai.com",
  "mikhail.nosikov@challenger.gauntletai.com",
  "monica.peters@gfachallenger.gauntletai.com",
  "naama.paulemont@challenger.gauntletai.com",
  "nayan.bhut@gfachallenger.gauntletai.com",
  "pavan.komateedi@challenger.gauntletai.com",
  "raq.robinson@challenger.gauntletai.com",
  "ryan.jagger@challenger.gauntletai.com",
  "sargon.benjamin@challenger.gauntletai.com",
  "scott.bushyhead@challenger.gauntletai.com",
  "scott.lydon@challenger.gauntletai.com",
  "shiv.kanthalu@challenger.gauntletai.com",
  "thalia.rossitter@challenger.gauntletai.com",
  "trevor.miller@challenger.gauntletai.com",
  "tyler.xia@challenger.gauntletai.com",
  "valeriia.muradian@challenger.gauntletai.com",
  "victor.rojas@challenger.gauntletai.com",
  "yeongbin.lee@challenger.gauntletai.com",
  "alan.nguyen@challenger.gauntletai.com",
  "alexander.gouyet@challenger.gauntletai.com",
  "dalton.dinderman@challenger.gauntletai.com",
  "dominic.antonelli@challenger.gauntletai.com",
  "jeremy.langer@challenger.gauntletai.com",
] as const;

export function normalizeRaterEmail(email: string): string {
  return email.trim().toLowerCase();
}

export const ALLOWED_RATERS = Array.from(new Set(RAW_ALLOWED_RATERS.map(normalizeRaterEmail))).sort();

export function isAllowedRater(email: string): boolean {
  return ALLOWED_RATERS.includes(normalizeRaterEmail(email));
}
