// Exercises the Pepsi generator boundary against clean, failed, and contaminated inputs.
import { access, chmod, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { assertSeedFixture } from '../src/contracts/index.ts';
import { buildRunTrace } from '../src/trace.ts';
import { capstoneDemoLens } from './lens-config.ts';
import { buildPepsiOutput, PEPSI_OUTPUT_SCHEMA_VERSION, type PepsiOutput, type PepsiOutputInput } from './pepsi-output.ts';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const generatedAt = '1970-01-01T00:00:00.000Z';

function fail(message: string): never {
  throw new Error(message);
}

async function loadInput(slug: string, label: string): Promise<PepsiOutputInput> {
  const fixturePath = path.join(root, 'fixtures', 'assay', `${slug}.json`);
  const fixture = assertSeedFixture(JSON.parse(await readFile(fixturePath, 'utf8')));
  const seedCasePath = `case-studies/${slug}/case-study.md`;
  const seedMarkdown = await readFile(path.join(root, seedCasePath), 'utf8');
  return {
    caseSlug: slug,
    caseLabel: label,
    caseStudyPath: seedCasePath,
    caseStudy: {
      title: fixture.seed.title,
      subtype: 'assay',
      status: 'seed-visible',
      paths: {
        caseStudy: seedCasePath,
      },
    },
    seedMarkdownBytes: Buffer.byteLength(seedMarkdown, 'utf8'),
    trace: buildRunTrace(fixture, 'diverge', { lenses: [capstoneDemoLens] }),
    generatedAt,
  };
}

async function writeExecutable(dir: string, name: string, contents: string): Promise<string> {
  const filePath = path.join(dir, name);
  await writeFile(filePath, contents, 'utf8');
  await chmod(filePath, 0o755);
  return filePath;
}

function assertStatus(output: PepsiOutput, label: string, generator: PepsiOutput['status']['generator'], source: PepsiOutput['status']['source']): void {
  if (output.status.generator !== generator || output.status.source !== source) {
    fail(`${label}: expected ${source}/${generator}, got ${output.status.source}/${output.status.generator}`);
  }
}

function validGeneratorSource(): string {
  return `#!/usr/bin/env node
let raw = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => { raw += chunk; });
process.stdin.on('end', () => {
  if (/solution\\.md|pepsi-segmentation|known[- ]solution|known-answer|known intervention|evaluator-only/i.test(raw)) {
    console.error('dirty request');
    process.exit(23);
  }
  const request = JSON.parse(raw);
  const packetId = 'pepsi:' + request.caseSlug + ':generator-check';
  process.stdout.write(JSON.stringify({
    schemaVersion: '${PEPSI_OUTPUT_SCHEMA_VERSION}',
    caseSlug: request.caseSlug,
    caseLabel: request.caseLabel,
    seedId: request.seedCase.seedId,
    runId: request.trace.runId,
    generatedAt: '${generatedAt}',
    status: { source: 'generator', generator: 'ok', ok: true, message: 'generated by harness' },
    primaryPacketId: packetId,
    packets: [{
      id: packetId,
      title: 'Generator check packet',
      claim: 'The generator boundary can return a complete Pepsi packet without seeing evaluator material.',
      subtype: 'test',
      sourceContext: request.seedCase.caseStudyPath,
      problemRecovery: {
        surfaceComplaint: request.trace.seed.prompt,
        deletedAssumption: 'A generator needs private evaluator fixtures to produce public output.',
        hiddenVariable: 'The request contract is enough to create an inspectable packet.',
        actualProblem: 'The live boundary must be useful without becoming an answer-key channel.',
        candidateResponse: 'Emit a complete packet from the clean request only.'
      },
      implicationMap: {
        disappears: ['Provider-specific SDK coupling'],
        getsCheaper: ['Boundary smoke testing'],
        winners: ['Static publish and local review'],
        losers: ['Fixture contamination'],
        secondOrderEffects: ['Generator failures become visible status instead of hidden crashes']
      },
      noveltyBasis: 'The packet is produced through the executable adapter, not by fixture segmentation.',
      groundingBasis: 'The request contains the public seed case path and RunTrace only.',
      falsifier: 'Fails if the request includes solution.md, pepsi-segmentation, or known-solution markers.',
      mechanismCost: 'One local executable that reads stdin and writes stdout.',
      lensFit: 'Confirms the Pepsi-first surface can consume provider-agnostic output.',
      lineage: {
        candidateIds: [],
        parent: 'seed:' + request.seedCase.seedId,
        generation: 0,
        operator: 'pepsi-generator-check',
        claimedDelta: 'Validated executable generator boundary.',
        nearestPrior: request.seedCase.seedId
      }
    }],
    tactics: []
  }));
});
`;
}

async function assertAbsent(filePath: string, label: string): Promise<void> {
  try {
    await access(filePath);
    fail(`${label}: generator command was invoked after request rejection`);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
  }
}

async function main(): Promise<void> {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), 'doppl-pepsi-generator-check-'));
  try {
    const cleanInput = await loadInput('fsd-accident-economy', 'FSD accident economy collapse');
    const contaminatedInput = await loadInput('jack-drone-privacy', 'Jack drone privacy');
    const nonzero = await writeExecutable(tempDir, 'nonzero.mjs', '#!/usr/bin/env node\nprocess.exit(7);\n');
    const malformed = await writeExecutable(tempDir, 'malformed.mjs', '#!/usr/bin/env node\nprocess.stdout.write("not json");\n');
    const timeout = await writeExecutable(tempDir, 'timeout.mjs', '#!/usr/bin/env node\nsetTimeout(() => {}, 30000);\n');
    const valid = await writeExecutable(tempDir, 'valid.mjs', validGeneratorSource());
    const trapPath = path.join(tempDir, 'trap-called');
    const trap = await writeExecutable(tempDir, 'trap.mjs', `#!/usr/bin/env node
import { writeFileSync } from 'node:fs';
writeFileSync(${JSON.stringify(trapPath)}, 'called');
process.stdout.write('{}');
`);

    assertStatus(await buildPepsiOutput(cleanInput), 'absent generator', 'not-configured', 'deterministic-fallback');
    assertStatus(await buildPepsiOutput({ ...cleanInput, generatorCommand: nonzero }), 'nonzero generator', 'exited-nonzero', 'deterministic-fallback');
    assertStatus(await buildPepsiOutput({ ...cleanInput, generatorCommand: malformed }), 'malformed generator', 'malformed-json', 'deterministic-fallback');

    const started = Date.now();
    const timeoutOutput = await buildPepsiOutput({ ...cleanInput, generatorCommand: timeout, timeoutMs: 150 });
    assertStatus(timeoutOutput, 'timeout generator', 'timeout', 'deterministic-fallback');
    if (Date.now() - started > 5_000) fail('timeout generator: child process was not capped quickly');

    const generated = await buildPepsiOutput({ ...cleanInput, generatorCommand: valid });
    assertStatus(generated, 'valid generator', 'ok', 'generator');
    if (generated.packets[0]?.title !== 'Generator check packet') fail('valid generator: generated packet was not rendered as primary output');

    const rejected = await buildPepsiOutput({ ...contaminatedInput, generatorCommand: trap });
    assertStatus(rejected, 'contaminated request', 'request-rejected', 'deterministic-fallback');
    await assertAbsent(trapPath, 'contaminated request');

    console.log('pepsi generator check passed: absent, nonzero, malformed, timeout, valid, contaminated-request');
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
